#!/bin/bash
# usage: ./reduce-all <opt-cores>

cd /opt/dataset
for f in *.rs; do reduce-file $f $1 1>/output/$f.normal.result 2>&1; done
#for f in *.rs; do reduce-file $f $1 "--enable-tree-slicer true" 1>/output/$f.tree.result 2>&1; done
#for f in *.rs; do reduce-file $f $1 "--enable-token-slicer true" 1>/output/$f.token.result 2>&1; done
# The new token slicer contains the tree slicer
for f in *.rs; do reduce-file $f $1 "--enable-token-slicer true" 1>/output/$f.both.result 2>&1; done
